apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-hello-world
  namespace: cosign
spec:
  replicas: 1 # kpt-set: ${replicas}
  selector:
    matchLabels:
      app: java-hello-world
  template:
    metadata:
      labels:
        app: java-hello-world
    spec:
      containers:
      - name: server
        image: asia-east1-docker.pkg.dev/shawn-demo-2022/image-repos/hello-world-java-docker
        ports:
        - containerPort: 8080 # kpt-set: ${containerPort}
        env:
        - name: PORT
          value: "8080" # kpt-set: ${containerPort}
        # This environment variable enables debugging support for the container.
        # Remove this to disable the debug build.
        - name: JAVA_TOOL_OPTIONS
          value: -agentlib:jdwp=transport=dt_socket,server=y,address=5005,suspend=n,quiet=y
        readinessProbe:
          tcpSocket:
            port: 8080 # kpt-set: ${containerPort}
          initialDelaySeconds: 5
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
