steps:
- id: 'kpt display'
  name: 'gcr.io/shawn-demo-2022/kpt:latest'
  entrypoint: 'sh'
  args:
  - '-c'
  - |
    kpt fn source .
- id: 'kpt render'
  name: 'gcr.io/shawn-demo-2022/kpt:latest'
  entrypoint: 'sh'
  args:
  - '-c'
  - |
    echo "***** before render"
    cat 1_hello.deployment.yaml
    kpt fn render
    echo "***** after render"
    cat 1_hello.deployment.yaml

